Andris
rajmunddongo/temalabor-vehicle-leasing pull request #2
Opened 2022-10-26 16:10 UTC by BAndriss

Komment a rentalhoz

2022-10-26 16:14 UTC, rajmunddongo commented
van amugy benne 2db conflict 
Conflicting files
src/main/java/hu/bme/aut/temalab/temalaborvehicleleasing/repository/RentalRepository.java
src/main/java/hu/bme/aut/temalab/temalaborvehicleleasing/service/RentalRelationshipsService.java

2022-10-26 18:09 UTC, BAndriss commented
yes láttom közbe elvileg a konfliktott javítottam (remélem jól csinálom) annyira még nem használtam még a github-ot

2022-10-26 18:46 UTC, rajmunddongo approved these changes
Nekem okes

2022-10-26 22:41 UTC, rajmunddongo commented
@ventt @adamgobhardter tőltetek is egy review-t pls

2022-10-26 22:44 UTC, ventt requested changes
Nincs test + streamekkel egyszerubb megoldani ezt

2022-10-27 04:22 UTC, adamgobhardter approved these changes

2022-10-27 08:56 UTC, BAndriss commented
tesztre nem azt mondta, hogy kövi mostani konzin lesz róla szó? és majd utána kell írni

2022-10-27 13:25 UTC, rajmunddongo commented
@ventt ha tényleg tetszenek a streamek akk egy approve-ot pls tolj

2022-10-27 13:25 UTC, ventt approved these changes

2022-10-27 13:25 UTC, merged