Issue#39 unless partof rental service mockito test
rajmunddongo/temalabor-vehicle-leasing pull request #42
Opened 2022-11-26 17:58 UTC by BAndriss

remove unused part (suggested by @adamgobhardter ) in RentalServiceTest
remove thinks in RentalServiceMockitoTest
closes #39

2022-11-26 20:33 UTC, adamgobhardter approved these changes

2022-11-26 20:38 UTC, adamgobhardter requested changes
A tearDown() metódus és a benne lévő törlés felesleges (RentalServiceMockitoTest), hiszen nincs db. Ezenkívül a setUp() metódus sem kell. :)

2022-11-26 20:44 UTC, adamgobhardter approved these changes

2022-11-27 11:51 UTC, rajmunddongo approved these changes

2022-11-27 11:53 UTC, merged